"""add sta

Revision ID: 1c4e34586a6a
Revises: c1ab68c02480
Create Date: 2025-05-14 20:31:19.417909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4e34586a6a'
down_revision: Union[str, None] = 'c1ab68c02480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('frequency_day', sa.Integer(), nullable=True),
    sa.Column('duration_day', sa.Integer(), nullable=True),
    sa.Column('given_up_day', sa.Integer(), nullable=True),
    sa.Column('task_breakdown', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_statistics',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_frequency', sa.Integer(), nullable=True),
    sa.Column('total_duration', sa.Integer(), nullable=True),
    sa.Column('average_daily_duration', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_statistics')
    op.drop_table('daily_statistics')
    # ### end Alembic commands ###
