""" update focus

Revision ID: 224982d1a34f
Revises: 9c89da23c99e
Create Date: 2025-05-18 10:54:00.117497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '224982d1a34f'
down_revision: Union[str, None] = '9c89da23c99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tasks', sa.Column('focus', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # op.add_column('tasks', sa.Column('focus_ratio', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('reference_expression1', sa.String(50), nullable=True))
    op.add_column('users', sa.Column('reference_expression2', sa.String(50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reference_expression2')
    op.drop_column('users', 'reference_expression1')
    # op.drop_column('tasks', 'focus_ratio')
    # op.drop_column('tasks', 'focus')
    # ### end Alembic commands ###
