"""update table--task and study room

Revision ID: 6e3d7a50ec7d
Revises: b5b2deeff775
Create Date: 2025-05-13 11:18:27.607871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e3d7a50ec7d'
down_revision: Union[str, None] = 'b5b2deeff775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_rooms', sa.Column('room_description', sa.String(255), nullable=True))
    op.add_column('tasks', sa.Column('time', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('given_up', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.drop_column('tasks', 'fin_time')
    op.drop_column('tasks', 'not_fin_time')
    op.drop_column('tasks', 'expected_fin_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('expected_fin_time', mysql.DATETIME(), nullable=True))
    op.add_column('tasks', sa.Column('not_fin_time', mysql.DATETIME(), nullable=True))
    op.add_column('tasks', sa.Column('fin_time', mysql.DATETIME(), nullable=True))
    op.drop_column('tasks', 'given_up')
    op.drop_column('tasks', 'time')
    op.drop_column('study_rooms', 'room_description')
    # ### end Alembic commands ###
