"""add study_room_id to users

Revision ID: 9c89da23c99e
Revises: c207536b5eaf
Create Date: 2025-05-15 12:36:21.146567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c89da23c99e'
down_revision: Union[str, None] = 'c207536b5eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('study_room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'study_rooms', ['study_room_id'], ['room_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'study_room_id')
    # ### end Alembic commands ###
