"""update table--task and study room

Revision ID: ab130161d39d
Revises: 6e3d7a50ec7d
Create Date: 2025-05-13 14:29:48.580468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ab130161d39d'
down_revision: Union[str, None] = '6e3d7a50ec7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'time',
               existing_type=mysql.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'time',
               existing_type=sa.Integer(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
